### ISSUE TITLE
Убрать поле из базы VehicleModification.vehicleYear

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#29]
проверить, удалить поле из базы VehicleModification.vehicleYear

зайти на форму менеджера и создать залог (выбрать авто, марку и модификацию), должно произойти сохранение данных по авто и информация должна пройти по всем этапам loanbroker bailverification loandeal

проверить как модели сортируются по году (выбирать год, модификации должны соответствовать с годом)

**Comment by lianlun1** [comment]
@yrics Надо протестировать на всех проектах, которые обращаются к каталогу: bailverification, loandeal, loanbroker

**Comment by lianlun1** [comment]
@vitavitall https://github.com/ilb/autocatalogs/blob/master/prisma/migrations/20230613092018_deleted_vehicle_from_names/migration.sql#L165

**Comment by lianlun1** [comment]
@Svet14Lana можно протестировать на loandeal и loanbroker

**Comment by vitavitall** [comment]
Принято
