### ISSUE TITLE
Убрать избыточные слова Vehicle в базе данных

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#30]
Очень много избыточных слов Vehicle в базе данных, нужно убрать префиксы

Проверить в bailverification, loandeal, loanbroker как получает данные и обрабатываются. 
- зайти на форму менеджера и создать залог (выбрать авто, марку и модификацию), должно произойти сохранение данных по авто и информация должна пройти по всем этапам loanbroker bailverification loandeal

**Comment by lianlun1** [comment]
@yrics Надо протестировать на всех проектах, которые обращаются к каталогу: bailverification, loandeal, loanbroker

**Comment by lianlun1** [comment]
@vitavitall https://github.com/ilb/autocatalogs/blob/master/prisma/migrations/20230613092018_deleted_vehicle_from_names/migration.sql

**Comment by vitavitall** [comment]
Принято
