### ISSUE TITLE
Реализовать отправку ошибок на почту

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#31]
Отсутствует отправка ошибок на почту

**Comment by yrics** [comment]
ссылка на библиотеку, которую нужно использовать 
mailer - https://github.com/iconicompany/imailer

**Comment by lianlun1** [comment]
@vitavitall Внес правки, необходимо протестировать

**Comment by vitavitall** [comment]
Ошибок в почте так и не удается увидеть.

Компонент отправки ошибок на почту должен оставаться в /ilb/ , а не переноситься в icompany .
Иначе весь проект autocatalog будет заморожен, так как не имеет полный цикл сборки и выкладки.

**Comment by yrics** [comment]
@MaximumQuiet Репозиторий mailer должен быть в орг-ции ilb, пакет с префиксом @ilb/
Есть проблема, что проекты называются одинаково.
Названия придумать и согласовать их с Виталием

**Comment by yrics** [comment]
@lianlun1 уточнить у Виталия

**Comment by yrics** [comment]
при автоматизированном обновлении справочника ошибка выходит и приходит письмо на почту (получателям ошибок). 
@vitavitall можно тестировать

**Comment by ForestLynx** [comment]
Виталий:
Автокаталог и его робот - принято с пролонгацией. Он не работает как нужно. Не должно быть письма, когда робот штатно отрабатывает. Письмо должно быть только когда ошибка в роботе. Это заваливает почту и порождает ложные реакции для админов.

**Comment by yrics** [comment]
оформить отдельную задачу
