### ISSUE TITLE
Чек-лист ПО autocatalogs. 1 этап [Ядро]

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#35]
Проект autocatalogs готов к выкладке 
необходимо оформить документацию по проекту по шаблону чек-листа ПО: 
https://docs.google.com/spreadsheets/d/1EeRGknuukswsnE7n9GpyW_BvaU9jPvUu2dtsEy_7VcQ/edit#gid=2080750544

Заполнить лист Autocatalogs пункты [Ядро]

Принимает работы по чек-листу ПО @vitavitall

**Comment by yrics** [comment]
@MaximumQuiet нужно смержить

**Comment by yrics** [comment]
На девеле Банка не работает, либо не удается пока убедиться в работоспособности. Пример, как можно проверить: 1. Скачиваем исходники проекта. 2. Собираем проект. 3. Указываем админский ящик получателя в processes.json. 4. И не меняя больше исходники проекта, запускаем проект. 5. Запускаем робота для загрузки объявлений (предварительно указать например левый путь до каталога с авито). 6. Итого в консоли есть ошибка, что путь не верный, а в почте письма нет.

**Comment by ForestLynx** [comment]
Давайте разделим задачу. Остальные пункты вынесем во вторую задачу.

**Comment by ForestLynx** [comment]
@vitavitall по пунктам
1.1,1.3, 2.1,2.3
4.2, 4.4, 5.1, 5.3, 5.8, 5.13
6.1,6.4,6.6,6.7,7.1
10.1,10.3, 10.4
 принято?

**Comment by yrics** [comment]
Доработки по чек-листу выполнены: 
4.3 Коды ответов ошибок (сделано)
5.11 Поддержка X-FORWARD-SECRET (сделано)
5.12 Наличие заглушек (сделано)
8.6 - Отправка ошибок на почту (обработчик ошибок). Решение найдено. Проверяют в ББ (на стороне банка)

[Чек-лист ПО autocatalogs. 1 этап [Ядро]. 2 часть#45](https://github.com/ilb/autocatalogs/issues/45)

**Comment by yrics** [comment]
8.6 - Отправка ошибок на почту (обработчик ошибок). 
нужна доработка

**Comment by vitavitall** [comment]
Часть работ принята, согласно текущим статусам в чек-листе. Остальные работы по другому issue.
