### ISSUE TITLE
Указать информацию в репозитории о заглушках в avito для скачивания json

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#38]
Создать заглушки на сторонние сервисы autocatalog (один вид и управление). Принцип описан в чек листе ПО раздел 5.1 https://docs.google.com/spreadsheets/d/1EeRGknuukswsnE7n9GpyW_BvaU9jPvUu2dtsEy_7VcQ/edit#gid=2080750544
Заглушки выносятся в отдельные xml/json/pdf/... файлы (/var/apps/<app>/stub/). 
Включение заглушек осуществляется через context.xml.

**Comment by dmitryi698** [comment]
@vitavitall сделал общий путь к заглушкам и отдельные включалки на тестовый каталог авито и тестовые ответы от сервиса

**Comment by yrics** [comment]
@MaximumQuiet нужно проверить и смержить

**Comment by yrics** [comment]
сделали заглушки на новый формат. Задача не актуальна
