### ISSUE TITLE
Чек-лист ПО autocatalogs. 1 этап [Ядро]. 2 часть

### ISSUE THREAD

**Issue by ForestLynx** [ilb/autocatalogs#45]
Продолжение задачи #35 

Доработки по чек-листу
тут нужна конкретика
4.3    Коды ответов ошибок (сделано)
5.11 Поддержка X-FORWARD-SECRET (сделано)
5.12 Наличие заглушек (сделано)
8.6 - Отправка ошибок на почту (обработчик ошибок). Решение найдено.  Проверяют в ББ (на стороне банка)

**Comment by yrics** [comment]
задачи выполнены в рамках Чек-лист ПО autocatalogs. 1 этап [Ядро]. 1 часть #35

**Comment by vitavitall** [comment]
4.3 - принято

5.11 - жду подтверждение от админов, надеюсь до 22.08.2023 будет обратная связь

5.12 - в целом принято
_только файл предлагаю перенести (чтобы было в общем стиле с другими проектами).
И еще по факту не проверял, что заглушка на авито корректно отрабатывает (после отпуска буду смотреть, но думаю все будет хорошо). Не стал сейчас включать, чтобы добить вопрос с отправкой ошибок в роботах, т.к. на подходе запуск следующих проектов с роботами, поэтому вопрос принципиальный (чтобы отладить на этом проекте правильный подход)._

8.6 - не получается запустить (мяч на стороне ЯК):

_(как будто не видит файл processes.json)_

 **HOME=/home/autocatalogs sudo -u autocatalogs DEBUG="icontext"  pm2 start `/usr/bin/npm run `catalogs:update`**
Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
    at setKey (node:internal/tls/secure-context:92:11)
    at configSecureContext (node:internal/tls/secure-context:174:7)
    at Object.createSecureContext (node:_tls_common:121:3)
    at Object.connect (node:_tls_wrap:1626:48)
    at Agent.createConnection (node:https:147:22)
    at Agent.createSocket (node:_http_agent:347:26)
    at Agent.addRequest (node:_http_agent:294:10)
    at new ClientRequest (node:_http_client:326:16)
    at request (node:https:357:10)
    at Agent._createProxyConnection (/home/autocatalogs/node_modules/better-https-proxy-agent/index.js:206:80) {
  opensslErrorStack: [ 'error:0906A065:PEM routines:PEM_do_header:bad decrypt' ],
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}

**Comment by ForestLynx** [comment]
По 8.6 играем без мяча. Совместно с ББ ищем решение.

**Comment by yrics** [comment]
8.6 на тестировании

**Comment by yrics** [comment]
@vitavitall просим проверить задачу

**Comment by yrics** [comment]
Принято (28.09.2023): принято
