### ISSUE TITLE
Исправление автоматизированных справочников autocatalogs

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#46]
__Проблема__  
_UserStory (JTBD)_
В проекте отсутствует crontab с настройками запуска, выгрузка справочников не обрабатывает переменные описанные в .pm2/process.env  

__Результат__  
Настроен автоматический запуск загрузки справочников.

__Решение__  
<strike>Запускать скрипты из /bin через pm2 start</strike>
Прописать SERVER_ADMIN в crontab (как шаблон)

__Как тестировать__  
В реальном окружении заполнить SERVER_ADMIN в crontab, применить конфигурацию, поменять в context.xml ссылку Авито на некорректную, дождаться письма об ошибке после выполнения скрипта. 

__Обратная совместимость__  
Совместимо

**Comment by yrics** [comment]
@vitavitall можно протестировать

**Comment by vitavitall** [comment]
А как найти crontab? Он куда-то переместился?

**Comment by MaximumQuiet** [comment]
> А как найти crontab? Он куда-то переместился?

На месте: https://github.com/ilb/autocatalogs/blob/master/conf/crontab
