### ISSUE TITLE
Чек-лист ПО autocatalogs. 2 этап 

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#48]
Проект autocatalogs в процессе выкладки.
Необходимо оформить документацию по проекту - вкладку autocatalogs в документе Чек-лист ПО
https://docs.google.com/spreadsheets/d/1EeRGknuukswsnE7n9GpyW_BvaU9jPvUu2dtsEy_7VcQ/edit#gid=2080750544
пункты:

- [ ] 2.3 Описание структуры (03.09.2023): пока норм, замечания?
- [ ] 4.1 Структура приложения НЕ СОГЛАСОВАНО
- [x] 4.3 Коды ответов ошибок (09.08.2023): принято
- [x] 4.4 Форматирование исходного кода (31.07.2023): принято
- [x] 5.1 Инструменты разработки (IDE)  (11.07.2023): принято
- [x] 5.4 Расположение сборщика проектов (28.09.2023): принято
- [ ] 5.6 Корректность версий проекта/компонентов
- [ ] 5.7 Карта точек входа (swagger, openapi)
- [x] 5.11 Поддержка X-FORWARD-SECRET (06.09.2023): принято
- [ ] 5.13 Подключен линтер исходного кода (ESLint, ...)
- [ ] 5.14 Передача времени с часовым поясом
- [x] 6.6 Отсутствие утечек персональных данных (11.07.2023): принято
- [x] 6.7 Способ авторизации (11.07.2023): принято
- [ ] 6.8 Закрываемые пути приложения
- [ ] 7.2 Наличие технического задания
- [ ] 9.5 Интеграция тестов с jenkins
- [x] 10.3 Отсутствие секретов в логах Виталий: принято
- [x] 10.4 Отсутствие персональных данных в логах Виталий: принято
- [ ] 10.5 Отсутствие любого удаленного логирования
- [ ] 11.1 Контроль качества исходного кода
- [ ] 11.2 Контроль проектирования базы данных
- [ ] 11.3 Контроль хранения файлового хранилища
- [ ] 11.4 Контроль логирования

Принимает работы по чек-листу ПО @vitavitall

**Comment by vitavitall** [comment]
Предлагаю закрыть эту задачу и перейти на 2 этап и добить остаток работ по техническому долгу

**Comment by MaximumQuiet** [comment]
обновил пункты "Готово на проверку"
