### ISSUE TITLE
Исправить hearbeat в autocatalogs

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#50]
Проблема
UserStory (JTBD)
heartbeat ресурс работает некорректно при отсутствии примененных миграций

Результат
heartbeat ресурс работает корректно при отсутствии примененных миграций

Решение
изменить проверяемый sql запрос в базе данных на:
select 1;

Как тестировать

Пересоздать базу данных, без миграций
Запустить приложение, вызвать /autocatalogs/api/heartbeat - в ответе должен быть статус 200
Обратная совместимость
совместимо

**Comment by MaximumQuiet** [comment]
@vitavitall можно проверять

**Comment by MaximumQuiet** [comment]
https://github.com/ilb/loanplatform/issues/31#issuecomment-1767666925
