### ISSUE TITLE
Расходятся модификации между autocatalogs и оценкой в ББ 

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#52]
Проблема
UserStory (JTBD)
Расходятся модификации между autocatalogs и оценкой в ББ

Что нужно сделать: запрос в carestimate (оценку авто) переделать в GET, с передачей параметров в query.

Результат
Модификации авто между autocatalogs и оценкой в ББ совпадают

**Comment by Svet14Lana** [comment]
@MaximumQuiet протестировано
Оценка прошла успешно

**Comment by valterch** [comment]
ошибка:

> 450: undefined url: https://tvicomplapp01.net.ilb.ru/icompproxy/web/proxy.php/carestimate/web//carestimate.php?hideEstimate-0=0&run-0=1&manufacturer-0=hyundai&model-0=solaris&age-0=2020&modification-0=15004&body-0=undefined&owners-0=undefined&region-0=74
> 
> Error: 450: undefined url: https://tvicomplapp01.net.ilb.ru/icompproxy/web/proxy.php/carestimate/web//carestimate.php?hideEstimate-0=0&run-0=1&manufacturer-0=hyundai&model-0=solaris&age-0=2020&modification-0=15004&body-0=undefined&owners-0=undefined&region-0=74
> at checkStatus (file:///srv/autochecks/node_modules/@ilb/uriaccessorjs/src/UriAccessorHttp.js:20:17)
> at fetchResponse (file:///srv/autochecks/node_modules/@ilb/uriaccessorjs/src/UriAccessorHttp.js:28:3)
> at UriAccessorHttp.getResponse (file:///srv/autochecks/node_modules/@ilb/uriaccessorjs/src/UriAccessorHttp.js:65:29)
> at processTicksAndRejections (node:internal/process/task_queues:96:5)
> at async UriAccessorHttp.getContent (file:///srv/autochecks/node_modules/@ilb/uriaccessorjs/src/UriAccessorHttp.js:73:22)
> at async CarEstimateGate.makeRequest (file:///srv/autochecks/src/app/checks/gates/CarEstimateGate.mjs:50:12)
> at async CarEstimateGate.getEstimate (file:///srv/autochecks/src/app/checks/gates/CarEstimateGate.mjs:35:22)
> at async CarEstimateProvider.check (file:///srv/autochecks/src/app/checks/providers/CarEstimateProvider.mjs:19:24)
> at async CheckService.executeSpecificCheckThrows (file:///srv/autochecks/src/app/services/CheckService.mjs:81:22)
> at async Array.<anonymous> (file:///srv/autochecks/src/core.js:9:22)

**Comment by Svet14Lana** [comment]
@yrics тестирование 20 мин.
