### ISSUE TITLE
Проверить выкладку autocatalogs на сервер Брокер, отключить autocatalogstest

### ISSUE THREAD

**Issue by MaximumQuiet** [ilb/autocatalogs#53]
Проблема: 
Справочники авто были запущены на тесте и использовались на проде. 
ББ запустил autocatalogs на проде и наш тест autocatalogstest нужно отключить. 

Результат: 
autocatalogstest отключен

Тестирование: 
проверить можно с админами ББ. На проде проверить загружаются ли каталоги, если да, то все в порядке.

**Comment by vitavitall** [comment]
Вроде все норм, и задачу можно закрывать
