### ISSUE TITLE
Передача параметров в автокаталог при запросе модификаций

### ISSUE THREAD

**Issue by yrics** [ilb/autocatalogs#54]
Файлы с ответами по модификациями:
Запрос с 2020 годом:
https://tvicomplapp01.net.ilb.ru/bailverificationv2/api/autocatalogs/modifications?withTransmission=true&modelName=4x4%20(%D0%9D%D0%B8%D0%B2%D0%B0)&modelId=329501&year=2020&query=
Есть модификация с id = 46772
[modifications (2020).json](https://github.com/ilb/bailverificationv2/files/14430343/modifications.2020.json)
[modifications (без года).json](https://github.com/ilb/bailverificationv2/files/14430344/modifications.json)

Запрос без года:
https://tvicomplapp01.net.ilb.ru/bailverificationv2/api/autocatalogs/modifications?withTransmission=true&modelName=4x4%20(%D0%9D%D0%B8%D0%B2%D0%B0)&modelId=329501&query=

Модификации id = 46772 нету

Тестирование: 
проверять по логам ББ

**Comment by valterch** [comment]
На сегодня id модификации для 2024 года = 46900 
по ссылке без года этой модификации не видно

**Comment by yrics** [comment]
добавили год, он тоже сейчас учитывается при поиске
@valterch 
просим проверить

**Comment by dmitryi698** [comment]
Скачал каталог Авито локально проверил с такими же вариантами запроса вот результат
С годом http://localhost:3000/autocatalogs/api/modifications?withTransmission=true&modelName=4x4%20(%D0%9D%D0%B8%D0%B2%D0%B0)&modelId=329501&year=2020&query=
[modifications.2020.json](https://github.com/ilb/autocatalogs/files/14518980/modifications.2020.json)
Без года: http://localhost:3000/autocatalogs/api/modifications?withTransmission=true&modelName=4x4%20(%D0%9D%D0%B8%D0%B2%D0%B0)&modelId=329501&query=
[modifications (без года).json](https://github.com/ilb/autocatalogs/files/14518986/modifications.json)

**Comment by yrics** [comment]
@valterch 
проверить перед релизом повторно. 
на 07.03.2024 - работает передача параметров.
